# This is the network config written by 'subiquity'
network:
  version: 2
  renderer: NetworkManager
  ethernets:
    enp3s0:
      dhcp4: true
  bridges:
    br0:
      interfaces: [enp3s0]
      dhcp4: true
