version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=claim-YqiMXUYdMzbBi8bKCR5N
    volumes:
      - /opt/multimedia/config-plex:/config
      - /storage/multimedia/tvseries:/tv
      - /storage/multimedia/movies:/movies
      - /storage/multimedia/music:/music
    restart: unless-stopped
    