version: '2'

volumes:
  nextcloud:
  db:
  onlyoffice-document-server:

services:
  db:
    container_name: nextcloud_db
    image: mariadb:10.5
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    container_name: nextcloud
    image: nextcloud
    restart: always
    ports:
      - 8085:80
    volumes:
      - ./config:/var/www/html/config
      - /storage/nextcloud/data:/var/www/html/data
    environment:
      - OVERWRITEHOST=cloud-sudeste.duckdns.org
      - OVERWRITEPROTOCOL=https
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db

  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    restart: always
    ports:
        - 8090:80
    volumes:
        - ./onlyoffice/data:/var/www/onlyoffice/Data
        - ./onlyoffice/logs:/var/log/onlyoffice