version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    ports:
      - 32400:32400
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=claim-KsgYfoAjXwXyGL27PxEW
    volumes:
      - /storage/plex/library:/config
      - /storage/plex/tvseries:/tv
      - /storage/plex/movies:/movies
      - /storage/plex/music:/music
    restart: unless-stopped