version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /storage/plex/library:/config
      - /storage/plex/tvseries:/tv
      - /storage/plex/movies:/movies
    restart: unless-stopped